name: apigateway-registry

on:
  push:
    branches:
      - main-apigateway
  jobs:
    build:
      name: "build apigateway"
      runs-on: ubuntu-latest
      steps:
        - name:
          uses: actions/checkout@v4

